version: '3'

services:
  backend:
    build: ./backend_py
    ports:
      - "8000:8000"
    volumes:
      - ./backend_py:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Assuming the frontend is listening on port 3000 internally
    depends_on:
      - backend

